vault:
  enabled: true
  address: "http://127.0.0.1:8200"  # Local development Vault URL
  secrets:
    openai: "secretv2/data/openai"
    smtp: "secretv2/data/smtp"
    notifications: "secretv2/data/notifications"
    security: "secretv2/data/security"

llm:
  use_openai_api: false
  openai:
    model: "gpt-4o"
    vault_api_key: "secretv2/data/openai"
    temperature: 0.5
    max_tokens: 4096
    top_p: 0.9
    frequency_penalty: 0.2
    presence_penalty: 0.3
    cache_responses: true
    retry_attempts: 3
  mistral:
    model: "mistral-7b"
    max_tokens: 1024
    temperature: 0.7

logging:
  level: "info"
  log_file: "app/logs/system/manus.log"    # System log - already correct
  audit_log: "app/logs/audit/audit.log"    # Audit log - already correct
  patterns_file: "app/config/patterns.json"  # Patterns file - already correct
  monitor_log: "app/logs/system/monitor.log"  # Added per feedback
  max_log_size: 10  # MB, for log rotation
  backup_count: 5   # Number of rotated log backups

agent_settings:
  max_tokens: 1000
  temperature: 0.7

security:
  vault_failure_mode: "fail"  # Stops execution if Vault is unavailable
  vault_path: "secretv2/data/security"
  password: null              # Use Vault for secure handling
  blocked_patterns: ["rm -rf", "shutdown", "format", "delete", "sudo", "chmod"]
  allowed_pattern: "^[a-zA-Z0-9\\s.,!?]+$"
  enforce_strict_validation: true
  max_input_length: 1000

smtp:
  use_vault: true
  vault_path: "secretv2/data/smtp"
  fallback:
    enabled: true
    server: "smtp.development.com"
    port: 587
    use_tls: true
    username: null  # Update with your username if using fallback
    password: null  # Update with your password if using fallback
    from_email: "dev_alerts@yourdomain.com"
  disable_on_vault_failure: true

notifications:
  use_vault: true
  vault_path: "secretv2/data/notifications"
  email: "notify@yourdomain.com"
  fallback_email: "backup@yourdomain.com"
  disable_on_vault_failure: true

system:
  low_power_mode: false
  compressible_weights: true
  allow_background_tasks: true

telemetry:
  enabled: false
  log_file: "app/logs/system/telemetry.log"  # Telemetry log - already correct

metrics_port: 8000
heartbeat_file: "app/logs/heartbeat.json"  # Heartbeat file - already correct
